version: '3.8'

services:
  web:
    build: 
      context: .
    image: dvmtask.azurecr.io/dvmtask
    container_name: dvmtask
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/dvm
    ports:
      - 8000:8000
  nginx:
    build: ./nginx
    image : nginx:latest
    container_name: dvmtask
    ports:
      - 1337:80
    depends_on:
      - web