version: '3.7'

services:
  web:
    build: 
      context: .
    command: gunicorn dvmtask.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/dvm
    ports:
      - 8000:8000
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web